# Generated by Django 3.2 on 2022-03-02 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0004_auto_20220225_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_blog', to=settings.AUTH_USER_MODEL),
        ),
    ]
