# Generated by Django 3.2 on 2022-03-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_snippet',
            field=models.CharField(default='click link to access blog post', max_length=255),
        ),
    ]
