# Generated by Django 3.2 on 2022-03-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_auto_20220306_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='leader_img',
            new_name='header_img',
        ),
    ]
