# Generated by Django 3.2 on 2022-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_auto_20220404_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images/'),
        ),
    ]
