# Generated by Django 3.2 on 2022-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_auto_20220404_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(default='placeholder', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images/profile/'),
        ),
    ]
