# Generated by Django 3.2 on 2022-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0018_auto_20220404_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='placeholder', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to='images/'),
        ),
    ]
