# Generated by Django 3.2 on 2022-04-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_auto_20220405_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, to='world.category'),
        ),
    ]
